# Generated by Django 4.1.7 on 2023-12-18 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Univers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univer_name', models.CharField(blank=True, db_index=True, max_length=30)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=20)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='', verbose_name='Аудио файл')),
                ('text', models.TextField(blank=True)),
                ('super_visor', models.CharField(max_length=20)),
                ('admin', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(default=False)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='analyzer.users')),
            ],
            options={
                'ordering': ['audio_file'],
            },
        ),
    ]
