# Generated by Django 4.1.7 on 2023-12-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='univers',
            old_name='number',
            new_name='correct_s_num',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='number',
            new_name='correct_s_num',
        ),
        migrations.AddField(
            model_name='univers',
            name='finished_s_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='univers',
            name='incorrect_s_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='univers',
            name='written_s_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='finished_s_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='incorrect_s_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='univer_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='analyzer.univers'),
        ),
        migrations.AddField(
            model_name='users',
            name='written_s_num',
            field=models.IntegerField(default=0),
        ),
    ]
