# Generated by Django 4.1.7 on 2023-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzer", "0004_rename_number_univers_correct_s_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="univers",
            name="univer_name",
            field=models.CharField(blank=True, db_index=True, max_length=31),
        ),
    ]
